name: CI Pipeline

on:
  pull_request:
    branches:
      - main
      - develop
      - 'feature/**'
  push:
    branches:
      - main
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Check formatting with Prettier
        run: npx prettier --check .

#  deploy:
#    needs: [lint, format]
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Use Node.js 18
#        uses: actions/setup-node@v3
#        with:
#          node-version: 18
#      - name: Install dependencies
#        run: npm ci
#      - name: Build project
#        run: npm run build
#      - name: Deploy to server
#        run: |
#          echo "Add your deployment script/commands here"
